name: free_games_giveaways
description: A new Flutter project.

publish_to: "none"

version: 2.5.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_bloc: ^7.1.0
  flutter_snake_navigationbar: ^0.5.0
  getwidget: ^2.0.1-nullsafety.4
  google_fonts: ^2.1.0
  octo_image: ^1.0.0+1
  url_launcher: ^6.0.9
  http: ^0.13.3
  share_plus: ^2.1.4
  flutter_local_notifications: ^8.1.1+1
  font_awesome_flutter: ^9.1.0
  flutter_form_builder: ^6.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  rflutter_alert: ^2.0.4
  firebase_crashlytics: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/licenses/
